// src/models/book.model.ts

/**
 * Defines the structure for a Book entity in the bookstore.
 */
export interface Book {
    id: number;
    title: string;
    author: string;
    genre: string;
    price: number; // Stored in dollars, required for discount calculation
}

/**
 * Defines the structure for creating a new book,
 * where the 'id' is typically generated by the system.
 */
export type CreateBookDTO = Omit<Book, 'id'>;